version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@volatile

executors:
  default:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/app

jobs:
  build:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install
      - run: bundle exec rake update_today

  update_yesterday:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install
      - run: bundle exec rake update_yesterday

  update_today:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install
      - run: bundle exec rake update_today

workflows:
  version: 2

  build:
    jobs:
      - build

  update_today:
    triggers:
      - schedule:
          # https://circleci.com/docs/2.0/workflows/#specifying-a-valid-schedule
          # Note: Cron step syntax (for example, */1, */20) is not supported.
          cron: "0 3,9,15,21 * * *" # 0 */6 * * * (JST)
          filters:
            branches:
              only: master

    jobs:
      - update_today

  update_yesterday:
    triggers:
      - schedule:
          # JST 0:05
          cron: "5 15 * * *"
          filters:
            branches:
              only: master

    jobs:
      - update_yesterday
