name: tweet_pixel_yesterday

on:
  workflow_dispatch:
  schedule:
    - cron: "5 15 * * *"

jobs:
  update_yesterday:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - run: bundle exec rake update_yesterday
        env:
          PIXELA_GRAPH_ID: ${{ secrets.PIXELA_GRAPH_ID }}
          PIXELA_TOKEN: ${{ secrets.PIXELA_TOKEN }}
          PIXELA_USERNAME: ${{ secrets.PIXELA_USERNAME }}
          TWITTER_ID: ${{ secrets.TWITTER_ID }}
