name: update_today

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3,9,15,21 * * *"

jobs:
  update_today:
    runs-on: ubuntu-latest
    name: update_today
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: bundle exec rake update_today
